name: Infrastructure Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - '**.tf'
      - 'environments/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: string

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Checkout Infrastructure
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        run: terraform -chdir=environments/${{ github.event.inputs.environment || 'dev' }} init -backend-config="path=terraform.tfstate"

      - name: Terraform Validate
        run: terraform -chdir=environments/${{ github.event.inputs.environment || 'dev' }} validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: |
          terraform -chdir=environments/${{ github.event.inputs.environment || 'dev' }} plan \
            -var="frontend_image=zoddo16/counterapp-ui:main" \
            -var="backend_image=zoddo16/counter-backend:main"

  apply:
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout Infrastructure
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform -chdir=environments/${{ github.event.inputs.environment || 'dev' }} init -backend-config="path=terraform.tfstate"

      - name: Terraform Apply
        run: |
          terraform -chdir=environments/${{ github.event.inputs.environment || 'dev' }} apply -auto-approve \
            -var="frontend_image=zoddo16/counterapp-ui:main" \
            -var="backend_image=zoddo16/counter-backend:main"

      - name: Show Outputs
        run: terraform -chdir=environments/${{ github.event.inputs.environment || 'dev' }} output

      - name: Verify Infrastructure
        run: |
          kubectl get all -n counterapp
          kubectl get ingress -n counterapp
