name: Infrastructure Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - '**.tf'
      - 'backend.tf'
      - 'main.tf'
      - 'variables.tf'
      - 'outputs.tf'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Infrastructure
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      continue-on-error: true
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Validate
      run: terraform validate
    
    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: |
        terraform plan \
          -var="frontend_image=zoddo16/counterapp-ui:main" \
          -var="backend_image=zoddo16/counter-backend:main"

  apply:
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    
    steps:
    - name: Checkout Infrastructure
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="frontend_image=zoddo16/counterapp-ui:main" \
          -var="backend_image=zoddo16/counter-backend:main"
    
    - name: Show Outputs
      run: terraform output
    
    - name: Verify Infrastructure
      run: |
        kubectl get all -n counterapp
        kubectl get ingress -n counterapp